version: "3.5"

services:
  backend:
    container_name: api
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - nginx_net
networks:
  nginx_net:
    external: true
